//
// this file is automatically generated
// by beaver.exe %BeaverVersion%
//

//
// if you want to use a private version file and customize this, see
// file://samsndrop02/CoreXT-Latest/docs/corext/corext/version.htm
//

#ifndef _BLDVER_H_
#define _BLDVER_H_

#define BUILD_NUMBER            "0.343"
#define BUILD_NUM               0,343
#define PRODUCT_NUMBER          "1.1"
#define PRODUCT_NUM             1,0
#define INET_VERSION            "1.1.0.343"
#define INET_VER                1,0,0,343

#define PRODUCT_MAJOR           1
#define PRODUCT_MAJOR_STRING    "1"
#define PRODUCT_MAJOR_NUMBER    1

#define PRODUCT_MINOR           1
#define PRODUCT_MINOR_STRING    "1"
#define PRODUCT_MINOR_NUMBER    0

#define BUILD_MAJOR             0
#define BUILD_MAJOR_STRING      "0"
#define BUILD_MAJOR_NUMBER      0

#define BUILD_MINOR             343
#define BUILD_MINOR_STRING      "343"
#define BUILD_MINOR_NUMBER      343

#ifdef DEBUG
    #define BUILD_FILEFLAGS_DEBUG   | VS_FF_DEBUG
#else
    #define BUILD_FILEFLAGS_DEBUG
#endif

#if defined(BUILD_LABBUILD)
    #if !defined(ENABLE_PRS_DELAYSIGN)
        #define BUILD_FILEFLAGS_RELEASE | VS_FF_PRERELEASE
    #else
        #define BUILD_FILEFLAGS_RELEASE
    #endif

    #ifndef BUILD_PRODUCTION
        #define BUILD_FILEFLAGS_SPECIAL | VS_FF_SPECIALBUILD
        #define BUILD_SPECIAL           "local"
    #else
        #define BUILD_FILEFLAGS_SPECIAL
    #endif

    #define BUILD_FILEFLAGS_PRIVATE
#else
    #define BUILD_FILEFLAGS_RELEASE
    #define BUILD_FILEFLAGS_SPECIAL
    #define BUILD_FILEFLAGS_PRIVATE | VS_FF_PRIVATEBUILD
    #define BUILD_PRIVATE           "local (by jrowlett on JROWLETT3)"
#endif

#define BUILD_FILEFLAGS         0x0L BUILD_FILEFLAGS_RELEASE BUILD_FILEFLAGS_SPECIAL BUILD_FILEFLAGS_PRIVATE BUILD_FILEFLAGS_DEBUG


#define VER_PRODUCTVERSION      1,0,0,343
#define VER_PRODUCTVERSION_STR  "1.0.0.343"
#define VER_PRODUCTVERSION_STR_FULL "1.1.0.343"
#define VER_PRODUCTVERSION_QSTR "1.1,0,343"
#define VER_PRODUCTVERSION_WSTR L"1.1.0.343"
#define VER_PRODUCTVERSION_W    ((1 << 8) | 1)
#define VER_PRODUCTMAJORVERSION 1
#define VER_PRODUCTMINORVERSION 1
//This is to appease a BuildDirectories.pm regex in finding the version part3 and we redefine it immediately after.
#define VER_PRODUCTBUILD            /* NT */   0
#define VER_PRODUCTBUILD        0
#define VER_PRODUCTBUILD_QFE    343
#define VER_PRODUCTNAME_STR     "Microsoft Account"
#define VER_COMPANYNAME_STR     "Microsoft Corporation"




#endif
